# In this config, you can tweak how certain interactions function.
# Any changes to this config will require either a server restart, or `/helditemsaver reload`.
Logging: true

# Items that Pokemon can not hold.
Blacklisted-Items:
  - "minecraft:barrier"
  - "minecraft:diamond_sword:1"

# Do not touch this. This is solely for future config updates.
Config-Version: 2.0